// Alle Date-Ideen mit Kategorien
const allDateIdeas = [
  // Romantisch
  {text: "Pralinen selber machen", categories: ["kreativ", "romantisch"]},
  {text: "Fotoshooting (er fotografiert sie)", categories: ["kreativ", "romantisch"]},
  {text: "Gegenseitiges Fotoshooting", categories: ["kreativ", "outdoor"]},
  {text: "Fotoshooting an cooler Location (altes Industriegebiet)", categories: ["kreativ", "abenteuer"]},
  {text: "Gemeinsamer IKEA/Möbelhaus-Besuch", categories: ["kreativ", "entspannt"]},
  {text: "Cocktails selbst mixen", categories: ["kreativ", "romantisch"]},
  {text: "Gemeinsam töpfern", categories: ["kreativ", "entspannt"]},
  {text: "Mit Fingerfarben malen", categories: ["kreativ", "romantisch"]},
  {text: "Landschaften malen", categories: ["kreativ", "entspannt"]},
  {text: "Portraits voneinander malen", categories: ["kreativ", "romantisch"]},

  // Aktiv
  {text: "Bladen oder Skaten gehen", categories: ["aktiv", "outdoor"]},
  {text: "Besuch in einer Rollerdisco", categories: ["aktiv", "abenteuer"]},
  {text: "Frisbee spielen", categories: ["aktiv", "outdoor"]},
  {text: "Badminton spielen", categories: ["aktiv", "outdoor"]},
  {text: "Tischtennis spielen", categories: ["aktiv", "outdoor"]},
  {text: "Speedminton spielen", categories: ["aktiv", "outdoor"]},
  {text: "Paintball spielen", categories: ["aktiv", "abenteuer"]},
  {text: "Erlebnispfade im Wald erkunden", categories: ["aktiv", "outdoor"]},
  {text: "Indoor Klettern", categories: ["aktiv", "abenteuer"]},
  {text: "Tretboot fahren", categories: ["aktiv", "romantisch", "outdoor"]},
  {text: "Ruderboot fahren", categories: ["aktiv", "romantisch", "outdoor"]},
  {text: "Mit dem Elektroboot fahren", categories: ["aktiv", "entspannt", "outdoor"]},
  {text: "Mit dem Schlauchboot fahren", categories: ["aktiv", "abenteuer", "outdoor"]},
  {text: "Schwimmen gehen", categories: ["aktiv", "outdoor"]},
  {text: "Nachtschwimmen", categories: ["aktiv", "romantisch", "abenteuer"]},
  {text: "Schwimmen im geschlossenen Freibad", categories: ["aktiv", "abenteuer", "romantisch"]},
  {text: "Schlittschuhlaufen", categories: ["aktiv", "romantisch"]},
  {text: "Schlittschuhlaufen mit Glühwein", categories: ["aktiv", "romantisch"]},
  {text: "Schlittschuhlaufen in der Innenstadt", categories: ["aktiv", "romantisch"]},
  {text: "Geocaching", categories: ["aktiv", "abenteuer", "outdoor"]},
  {text: "Crossgolfen", categories: ["aktiv", "outdoor"]},
  {text: "Probetanzstunde nehmen", categories: ["aktiv", "romantisch"]},
  {text: "Tanzparty oder Salsaparty besuchen", categories: ["aktiv", "romantisch"]},
  {text: "Billard spielen", categories: ["aktiv", "entspannt"]},
  {text: "Minigolf spielen", categories: ["aktiv", "entspannt"]},
  {text: "Skifahren gehen", categories: ["aktiv", "outdoor", "abenteuer"]},
  {text: "Snowboarden gehen", categories: ["aktiv", "outdoor", "abenteuer"]},
  {text: "Erlebnisbad besuchen", categories: ["aktiv", "entspannt"]},
  {text: "Miramar besuchen", categories: ["aktiv", "entspannt"]},
  {text: "Alpamare besuchen", categories: ["aktiv", "entspannt"]},
  {text: "Thermenbesuch", categories: ["aktiv", "entspannt", "romantisch"]},
  {text: "Schlittenfahren", categories: ["aktiv", "outdoor"]},
  {text: "Nacht-Schlittenfahren", categories: ["aktiv", "outdoor", "romantisch"]},
  {text: "Schlittenfahren mit Glühwein", categories: ["aktiv", "outdoor", "romantisch"]},
  {text: "Bowling spielen", categories: ["aktiv", "entspannt"]},
  {text: "Go-Kart fahren", categories: ["aktiv", "abenteuer"]},
  {text: "Tandem fahren", categories: ["aktiv", "outdoor", "romantisch"]},
  {text: "Drachen steigen lassen", categories: ["aktiv", "outdoor"]},
  {text: "Canyoning", categories: ["aktiv", "abenteuer", "outdoor"]},
  {text: "Schneemann oder Iglu bauen", categories: ["aktiv", "outdoor", "romantisch"]},
  {text: "Schneeballschlacht", categories: ["aktiv", "outdoor"]},
  {text: "Modellflugzeug fliegen", categories: ["aktiv", "outdoor"]},
  {text: "Modellschiff fahren", categories: ["aktiv", "outdoor"]},
  {text: "Modellauto fahren", categories: ["aktiv", "outdoor"]},
  {text: "Kitesurf Schnupperkurs", categories: ["aktiv", "abenteuer", "outdoor"]},
  {text: "Golf Schnupperstunden", categories: ["aktiv", "outdoor"]},
  {text: "Erdbeeren pflücken", categories: ["aktiv", "outdoor", "romantisch"]},

  // Chillig
  {text: "Café oder Coffee Shop besuchen", categories: ["entspannt", "romantisch"]},
  {text: "Shisha Café besuchen", categories: ["entspannt"]},
  {text: "Lounge besuchen", categories: ["entspannt", "romantisch"]},
  {text: "Gemütliche Bar besuchen", categories: ["entspannt", "romantisch"]},
  {text: "Strandbar besuchen", categories: ["entspannt", "romantisch", "outdoor"]},
  {text: "Gemeinsam shoppen gehen", categories: ["entspannt"]},
  {text: "Schaufensterbummel machen", categories: ["entspannt", "romantisch"]},
  {text: "Festival besuchen", categories: ["entspannt", "abenteuer"]},
  {text: "Flohmarktbummel", categories: ["entspannt", "kreativ"]},
  {text: "Gemeinsam Eis essen", categories: ["entspannt", "romantisch"]},
  {text: "Spaziergang im Park", categories: ["entspannt", "romantisch", "outdoor"]},
  {text: "Spaziergang im Schlosspark", categories: ["entspannt", "romantisch", "outdoor"]},
  {text: "Waldspaziergang", categories: ["entspannt", "outdoor"]},
  {text: "Nachtspaziergang mit Fackeln", categories: ["entspannt", "romantisch", "outdoor"]},
  {text: "Wellnesstag zuhause", categories: ["entspannt", "romantisch"]},
  {text: "Wellnesstag im Hotel", categories: ["entspannt", "romantisch"]},
  {text: "Museumsbesuch", categories: ["entspannt", "kreativ"]},
  {text: "Museum mit Versuchsvorführungen", categories: ["entspannt", "kreativ"]},
  {text: "Interaktives Museum besuchen", categories: ["entspannt", "kreativ"]},
  {text: "Ausstellung besuchen", categories: ["entspannt", "kreativ"]},
  {text: "Körperwelten-Ausstellung besuchen", categories: ["entspannt", "kreativ"]},
  {text: "Außergewöhnliche Ausstellung besuchen", categories: ["entspannt", "kreativ"]},
  {text: "Interessante Messe besuchen", categories: ["entspannt", "kreativ"]},
  {text: "Picknick mit Aussicht", categories: ["entspannt", "romantisch", "outdoor"]},
  {text: "Picknick auf einem Dach", categories: ["entspannt", "romantisch", "abenteuer"]},
  {text: "Picknick in schöner Natur", categories: ["entspannt", "romantisch", "outdoor"]},
  {text: "Picknick vor toller Kulisse", categories: ["entspannt", "romantisch", "outdoor"]},
  {text: "Picknick im Maisfeld", categories: ["entspannt", "romantisch", "outdoor"]},
  {text: "Stadtführung machen", categories: ["entspannt", "kreativ"]},
  {text: "Persönliche Stadtführung (von ihm für sie)", categories: ["entspannt", "romantisch", "kreativ"]},
  {text: "Biergarten besuchen", categories: ["entspannt"]},
  {text: "Ins Kino gehen", categories: ["entspannt", "romantisch"]},
  {text: "Open Air Kino besuchen", categories: ["entspannt", "romantisch", "outdoor"]},
  {text: "Autokino besuchen", categories: ["entspannt", "romantisch"]},
  {text: "3D/4D/IMAX-Kino besuchen", categories: ["entspannt", "abenteuer"]},
  {text: "Theater besuchen", categories: ["entspannt", "romantisch"]},
  {text: "In die Oper gehen", categories: ["entspannt", "romantisch"]},
  {text: "Musical besuchen", categories: ["entspannt", "romantisch"]},
  {text: "Improtheater besuchen", categories: ["entspannt", "kreativ"]},
  {text: "Improoper besuchen", categories: ["entspannt", "kreativ"]},
  {text: "Schifffahrt machen", categories: ["entspannt", "romantisch"]},
  {text: "Sauna besuchen", categories: ["entspannt", "romantisch"]},
  {text: "Saunalandschaft besuchen", categories: ["entspannt", "romantisch"]},
  {text: "Türkisches Hamam besuchen", categories: ["entspannt", "romantisch"]},
  {text: "Sushibar besuchen", categories: ["entspannt"]},
  {text: "Sushi-Fließband-Restaurant besuchen", categories: ["entspannt", "kreativ"]},
  {text: "Weihnachtsmarkt besuchen", categories: ["entspannt", "romantisch"]},
  {text: "Lokales Kulturangebot besuchen", categories: ["entspannt", "kreativ"]},
  {text: "DVD-Abend machen", categories: ["entspannt", "romantisch"]},
  {text: "DVD-Abend an ungewöhnlichen Orten (im Kombi/im Zelt)", categories: ["entspannt", "romantisch", "kreativ"]},
  {text: "Eishockeyspiel im Stadion anschauen", categories: ["entspannt", "abenteuer"]},
  {text: "Fußballspiel anschauen", categories: ["entspannt", "abenteuer"]},
  {text: "Formel 1 anschauen", categories: ["entspannt", "abenteuer"]},
  {text: "Pyjama-Party", categories: ["entspannt", "romantisch"]},
  {text: "Dinner zu Hause", categories: ["entspannt", "romantisch"]},
  {text: "Dinner von einem Mietkoch zubereiten lassen", categories: ["entspannt", "romantisch"]},
  {text: "Angeln gehen", categories: ["entspannt", "outdoor"]},
  {text: "Weinprobe machen", categories: ["entspannt", "romantisch"]},
  {text: "Brettspiele spielen", categories: ["entspannt", "kreativ"]},
  {text: "Floating ausprobieren", categories: ["entspannt"]},

  // Faszinierend
  {text: "Aussichtsplattform des Flughafens besuchen", categories: ["faszinierend", "entspannt"]},
  {text: "Aussichtsplattform auf Bergen besuchen", categories: ["faszinierend", "outdoor", "romantisch"]},
  {text: "Aussichtsplattform auf Gebäuden besuchen", categories: ["faszinierend", "romantisch"]},
  {text: "Aussichtsplattform bei Dunkelheit besuchen", categories: ["faszinierend", "romantisch"]},
  {text: "Planetarium besuchen", categories: ["faszinierend", "romantisch"]},
  {text: "Sternwarte besuchen", categories: ["faszinierend", "romantisch"]},
  {text: "Natürliche Sehenswürdigkeiten besichtigen", categories: ["faszinierend", "outdoor"]},
  {text: "Natürliche Sehenswürdigkeiten mit Proviant besichtigen", categories: ["faszinierend", "outdoor", "romantisch"]},
  {text: "Burg oder Schloss besichtigen", categories: ["faszinierend", "romantisch"]},
  {text: "Erlebnisrestaurant besuchen", categories: ["faszinierend", "romantisch"]},
  {text: "Lying Dinner erleben", categories: ["faszinierend", "romantisch"]},
  {text: "Restaurant auf Aussichtstürmen besuchen", categories: ["faszinierend", "romantisch"]},
  {text: "Dunkelrestaurant besuchen", categories: ["faszinierend", "abenteuer", "romantisch"]},
  {text: "Rittermahl erleben", categories: ["faszinierend", "abenteuer"]},
  {text: "Zirkus besuchen", categories: ["faszinierend", "entspannt"]},
  {text: "Hubschrauber-Rundflug", categories: ["faszinierend", "abenteuer", "romantisch"]},
  {text: "Rundflug mit kleinem Flieger", categories: ["faszinierend", "abenteuer", "romantisch"]},
  {text: "Aussichtsturm besuchen", categories: ["faszinierend", "romantisch"]},
  {text: "Ballonfahrt machen", categories: ["faszinierend", "abenteuer", "romantisch"]},
  {text: "Sterne beobachten", categories: ["faszinierend", "romantisch", "outdoor"]},
  {text: "Sterne mit Teleskop beobachten", categories: ["faszinierend", "romantisch", "outdoor"]},
  {text: "Salzbergwerk besichtigen", categories: ["faszinierend", "abenteuer"]},
  {text: "Nostalgiefotos machen lassen", categories: ["faszinierend", "kreativ", "romantisch"]},
  {text: "Escape Room besuchen", categories: ["faszinierend", "abenteuer"]},
  {text: "Indoor Skydiving ausprobieren", categories: ["faszinierend", "abenteuer"]},

  // Abenteuerlich
  {text: "Zoo besuchen", categories: ["abenteuer", "outdoor"]},
  {text: "Wildpark besuchen", categories: ["abenteuer", "outdoor"]},
  {text: "Alpentierpark besuchen", categories: ["abenteuer", "outdoor"]},
  {text: "Spielhalle besuchen", categories: ["abenteuer", "entspannt"]},
  {text: "Karaoke Bar besuchen", categories: ["abenteuer", "kreativ"]},
  {text: "Kissenschlacht machen", categories: ["abenteuer", "romantisch"]},
  {text: "Kasino besuchen", categories: ["abenteuer", "entspannt"]},
  {text: "Labyrinth im Maisfeld erkunden", categories: ["abenteuer", "outdoor", "romantisch"]},
  {text: "Kurztrip in die Berge", categories: ["abenteuer", "outdoor", "romantisch"]},
  {text: "Kurztrip nach Paris", categories: ["abenteuer", "romantisch"]},
  {text: "Kurztrip ans Meer", categories: ["abenteuer", "outdoor", "romantisch"]},
  {text: "Sommerrodelbahn ausprobieren", categories: ["abenteuer", "outdoor"]},
  {text: "Freizeitpark besuchen", categories: ["abenteuer", "romantisch"]},
  {text: "Westernpark besuchen", categories: ["abenteuer", "kreativ"]},
  {text: "Floßfahrt machen", categories: ["abenteuer", "outdoor", "romantisch"]},
  {text: "Bungee-Springen", categories: ["abenteuer", "outdoor"]},
  {text: "Rafting ausprobieren", categories: ["abenteuer", "outdoor"]},
  {text: "Bodyflying ausprobieren", categories: ["abenteuer"]},
  {text: "Fallschirmspringen", categories: ["abenteuer", "outdoor"]},
  {text: "Pilze suchen", categories: ["abenteuer", "outdoor"]},
  {text: "Ausflug ins Blaue machen", categories: ["abenteuer", "romantisch"]},
  {text: "Ritterfest besuchen", categories: ["abenteuer", "kreativ"]},
  {text: "Segway Tour machen", categories: ["abenteuer", "outdoor"]},
  {text: "Segeltour machen", categories: ["abenteuer", "outdoor", "romantisch"]},
  {text: "Hochseilgarten besuchen", categories: ["abenteuer", "outdoor"]}
];
